server:
  url: http://localhost:8080

security:
  password-hashing:
    secret: ""
    salt-length: 16
    iterations: 31000
    algorithm: PBKDF2WithHmacSHA256
  enforce-https:
    password-transfer: true

websockets:
  # Hostname to listen at. Leave empty for 0.0.0.0 or ::0.
  listen-address:
  # Port for listening at for websocket connections
  listen-port: 8081
  # The allowed origin for the websocket connection
  allowed-origin:
  # Public port for websocket connections
  published-port: 8081
  # Web socket protocol
  protocol: wss

storage:
  s3:
    endpoint:
    accessKey:
    secretKey:
    bucket: poker
    encryptionKey:

avatars:
  dicebear:
    uri: http://localhost:3000/6.x/adventurer/svg