name: Create release image and deploy
run-name: Release and deploy ${{ github.ref_name }}
on:
  push:
    tags:
      - 'v*'
env:
  VERSION: ${{ github.ref_name }}
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
      - run: cd ${{ github.workspace }}
      - run: ./gradlew build -x test
      - run: docker build -t "docker.matthias-fisch.de/poker-server:$VERSION" .
      - env:
          DOCKER_SECRET: ${{ secrets.DOCKER_PASSWORD }}
        run: docker login -u github -p "$DOCKER_SECRET" docker.matthias-fisch.de
      - run: docker push "docker.matthias-fisch.de/poker-server:$VERSION"
      - run: docker tag "docker.matthias-fisch.de/poker-server:$VERSION" "docker.matthias-fisch.de/poker-server:latest"
      - run: docker push "docker.matthias-fisch.de/poker-server:latest"