name: Create release image and deploy
run-name: Release and deploy ${{ github.ref_name }}
on:
  push:
    branches:
      - develop
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
      - run: cd ${{ github.workspace }}
      - name: Build and push images
        env:
          DOCKER_SECRET: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          TAG=$(./gradlew properties -q | grep "^version:" | awk '{print $2}')
          IMAGE_NAME="docker.matthias-fisch.de/poker-server:$TAG"
          echo "Image will be available as $IMAGE_NAME."
          docker build -t "$IMAGE_NAME" .
          docker login -u github -p "$DOCKER_SECRET" docker.matthias-fisch.de
          docker push "$IMAGE_NAME"
          docker tag "$IMAGE_NAME" "docker.matthias-fisch.de/poker-server:latest"
          docker push "docker.matthias-fisch.de/poker-server:latest"