name: Test changes
run-name: Running for commit ${{ github.sha }} on ${{ github.ref_name }}
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.8.0
        with:
          mongodb-version: 6.0
          mongodb-username: root
          mongodb-password: test
          mongodb-db: poker
      - run: "docker exec mongo mongosh -u root -p test --eval 'db.createUser({user: \"test1\", pwd: \"test\", roles: [{role: \"readWrite\", db: \"poker\"}]})'"
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
      - run: java -version
      - run: cd ${{ github.workspace }}
      - run: ./gradlew test
      - name: Archive test results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-report
          path: build/reports/tests