name: Test ${{ github.ref_name }}
run-name: Running for commit ${{ github.sha }} on ${{ github.ref_name }}
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
      - run: java -version
      - run: cd ${{ github.workspace }}
      - name: Deploy database
        run: docker-compose -f .github/deployment/docker-compose.yml up -d
      - run: ./gradlew test
      - name: Archive test results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-report
          path: build/reports/tests